#data-api-key: 3g%2Fd4w%2FtARZLfMnVnR4Qp%2FBSmp5Y6ruf5IH9X1FIgMomKQQYCbI5pn1NBlKWJDQgfkswjUJfBwVfp5tT%2FGTU4g%3D%3D
# nasa-api
api-key: Rg8aLCbBMc0HGHey5sZwSFRdJ3qvOM5CeRRtxeoU
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hellordb
    username: hellotoday
    password: 1016
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 시작 시 테이블을 자동으로 생성/업데이트할지 설정
    show-sql: true # SQL 쿼리를 콘솔에 출력할지 설정
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.data.mongodb.database}?authSource=${spring.data.mongodb.authentication-database}&readPreference=primaryPreferred&directConnection=true
      authentication-database: admin
      port: 27017
      host: localhost
      database: hellonosql
server:
  port: 8090